<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/20/16 08:32:36
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetCategory extends BaseJobeetCategory {
    
    public function __toString()
    {
            return $this->getName();
    }
    
    public function getActiveJobs($max) {
        $criteria = new Criteria();
        $criteria->add(JobeetJobPeer::CATEGORY_ID, $this->getId());
        $criteria->setLimit($max);
        
        return JobeetJobPeer::getActiveJobs($criteria);
    }

} // JobeetCategory
